"""Assemble PostgreSQL's runtime closure, preserving Debian provenance/locales."""
import json
import re
import shutil
import subprocess
from pathlib import Path

root = Path('/runtime')
root.mkdir()
shutil.copytree('/opt/postgresql', root / 'opt/postgresql', symlinks=True)
copied = set()

def copy_file(source):
    source = Path(source)
    if str(source).startswith('/opt/postgresql/'):
        return
    target = root / source.relative_to('/')
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, target)
    copied.update((str(source), str(source.resolve())))

# initdb/pg_ctl require a shell; dash has no terminal/ACL dependency.
seeds = [Path('/bin/sh')]
for binary in Path('/opt/postgresql').rglob('*'):
    if binary.is_file():
        with binary.open('rb') as stream:
            if stream.read(4) == b'\x7fELF':
                seeds.append(binary)
for binary in seeds:
    copy_file(binary)
    result = subprocess.run(['ldd', str(binary)], capture_output=True, text=True)
    if 'not found' in result.stdout:
        raise RuntimeError(f'Missing dependency for {binary}: {result.stdout}')
    for library in re.findall(r'(?:=>\s+|^\s*)(/\S+)', result.stdout, re.M):
        copy_file(library)
for source in ('/etc/nsswitch.conf', '/etc/os-release', '/usr/lib/os-release', '/etc/debian_version',
               '/usr/lib/locale/locale-archive', '/etc/ssl/certs/ca-certificates.crt'):
    copy_file(source)
packages = set()
for listing in Path('/var/lib/dpkg/info').glob('*.list'):
    if any(line in copied for line in listing.read_text().splitlines()):
        packages.add(listing.name.removesuffix('.list').split(':')[0])
# locale-archive is generated by the locales package, not in its file list.
packages.add('locales')
records = []
for record in Path('/var/lib/dpkg/status').read_text().split('\n\n'):
    match = re.search(r'^Package: (.+)$', record, re.M)
    if match and match[1] in packages:
        records.append(record)
        license_file = Path('/usr/share/doc') / match[1] / 'copyright'
        if license_file.exists():
            copy_file(license_file)
(root / 'var/lib/dpkg').mkdir(parents=True)
(root / 'var/lib/dpkg/status').write_text('\n\n'.join(records) + '\n\n')
(root / 'opt/postgresql/debian-files.json').write_text(json.dumps(
    {'packages': sorted(packages), 'files': sorted(copied)}, indent=2) + '\n')
(root / 'etc/passwd').write_text('postgres:x:999:999:PostgreSQL:/var/lib/postgresql:/bin/sh\n')
(root / 'etc/group').write_text('postgres:x:999:\n')
for directory in ('tmp', 'var/run/postgresql'):
    path = root / directory
    path.mkdir(parents=True, exist_ok=True)
    path.chmod(0o1777)
print('PostgreSQL runtime Debian components:', ', '.join(sorted(packages)))
