import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';

const require = createRequire(import.meta.url);
const packagePath = require.resolve('@alpinejs/csp/package.json');
const { version } = JSON.parse(await readFile(packagePath, 'utf8'));
const source = await readFile(resolve(dirname(packagePath), 'dist/cdn.min.js'), 'utf8');
const output = `/** Alpine.js CSP ${version} — MIT; generated by npm run vendor:sync. */\n${source}`;
const destination = new URL('../web/public/static/vendor/alpine.csp.min.js', import.meta.url);
if (process.argv.includes('--check')) {
  if (await readFile(destination, 'utf8') !== output) {
    throw new Error('Public Alpine asset is stale. Run npm run vendor:sync.');
  }
} else {
  await writeFile(destination, output);
}
